[package]
name = "the_zord"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust_ffi = { path = "../../bindings/rust_ffi" }
tiny_lib = { path = "../../bindings/tiny_lib-ffi" }
